### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by majedbawarshi** [IniasP/rnnoise-cli#4] opened 2022-01-07 07:47 UTC
The package code has a lack of documentation, which makes the usage of the package or contribution to the repository time-consuming, I would appreciate it if you start working on code documentation to get some contributors to the repository.

**Comment by IniasP** [comment] 2022-01-07 12:44
I'll add more in-code documentation when I have some time. I was also thinking about adding type hinting stubs for the parts of the `pulsectl` lib that are used.
Just using the CLI application should be straightforward.

Aside from the `rnnoise` command, the pulse submodule could just be used as a Python library as well, although that's not really what I intended for now. If that's what you mean by usage, then I agree its interface is poorly documented.

Can I ask why this is an issue for you? Did you want to use or contribute something specific?

**Comment by majedbawarshi** [comment] 2022-01-07 14:08
Thank you for your quick and informative reply,
Yes, I wanted to use the package as a python interface but I couldn't figure out how to use the package as an interface for my python code if I want to use it as a parent class rather than having to deal with it from CLI.

Regarding the contribution, yes I would love to contribute to this package because it is the only python package out there that deals with the librnnoise_ladspa.so binary file correctly using the python language. 

Also, I would like to mention that I've encountered a problem once I installed the package. it was giving me an error about not finding the librnnoise_ladspa.so file inside the package directory inside my Linux OS files, I had to do it manually by booting my PC into root mode and giving the security privilege for the user to add files to the package directory and booting my system again and that when I was able to add the file successfully and run the package without an error.

**Comment by IniasP** [comment] 2022-01-07 15:41
> Also, I would like to mention that I've encountered a problem once I installed the package. it was giving me an error about not finding the librnnoise_ladspa.so file inside the package directory inside my Linux OS files, I had to do it manually by booting my PC into root mode and giving the security privilege for the user to add files to the package directory and booting my system again and that when I was able to add the file successfully and run the package without an error.

I can't reproduce that, sorry. It may be very specific to your python setup, maybe try a virtual environment and see if that works. If it's a permission issue then either running the `pip install --user rnnoise-cli` instead or `sudo pip install rnnoise-cli` may fix something, but I'm not familiar with what those methods imply for the install.

Regarding documentation, sadly I have exams to deal with at the moment 😅.
Of course, you can import the [`PulseInterface`](https://github.com/IniasP/rnnoise-cli/blob/c94525bf6eb910909605471ca3d37e1a294ecc29/src/rnnoise_cli/pulse/pulse.py#L44) as `from rnnoise_cli.pulse import PulseInterface`.
Check out how [the activate command](https://github.com/IniasP/rnnoise-cli/blob/c94525bf6eb910909605471ca3d37e1a294ecc29/src/rnnoise_cli/commands.py#L91) calls `obtain_device`, which uses `PulseInterface.get_source(device_str)` to get a pulse source from the `pulsectl` library (these pulse devices are what I mentioned I'd like to add type hints for sometime).
If you have a device, activating the plugin is a matter of calling `PulseInterface.load_modules` with the device you obtained and the control level.
Hope that helps for now if you want to play with it ASAP.

**Comment by IniasP** [comment] 2022-02-05 19:47
Finally got done with those exams lol.

I've added some docstrings in `pulse.py` (cb4fed608833281adc4a84ce6305483eadfd45cf) and did the type stubs for `pulsectl` so everything is nicely type hinted (02c1d7b65ae4f7d31b707c80bf9291d17160d41a). Both should be of at least some help to anyone struggling to understand or use the code.

I'm not really planning to go much beyond this, so I'm closing this issue. If you have any other concerns, feel free to share them.

**Closed by IniasP** 2022-02-05 19:47 UTC
